#!/bin/bash

# fire notification in given number of minutes
TIMER=0
BREAK=5
CUR_DIR=/home/nika/bin-assets/alarm-notification/
if [ $1 = "--help" ]
then cat $CUR_DIR/README.md
else

if [ -n "$1" ]
then TIMER=$1
fi
if [ -n "$2" ]
then BREAK=$2
fi

echo "notify-send -u critical -t 0 -i $CUR_DIR/alarm-notification.png 'Time is up' '$TIMER min is over, $BREAK min break' && aplay $CUR_DIR/alarm-notification.wav" | at now + $TIMER minutes
fi

